//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libmanage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int BookId { get; set; }
        public string ISBNnumber { get; set; }
        public string BookName { get; set; }
        public string BookDescription { get; set; }
        public string BookLanguage { get; set; }
        public string Categories { get; set; }
        public string Publisher { get; set; }
        public string PublishedYear { get; set; }
        public string Author { get; set; }
    }
}
